login:
    path: /login
    controller: App\Controller\LoginController::mostrarLogin


stockp:
    path: /stockp
    controller: App\Controller\StockController::mostrarStock
    
princ:
    path: /princ
    controller: App\Controller\GestionController::listarCategorias    

